config/routes.rb
Rails.application.routes.draw do
  resources :tournaments, except: :show do
    member do
      get 'results'
      post 'team_scores_update'
    end
  end

  get '/user_role_request/:id/approve', to: 'user_role_requests#approve', as: 'approve_user_role_request'
  get '/user_role_request/:id/deny', to: 'user_role_requests#deny', as: 'deny_user_role_request'

  get '/profile', to: 'users#profile'

  get '/tournaments/administration/:id/:round', to: 'tournaments#administration', as: 'administration_tournament'
  get '/tournaments/display/:id/:court', to: 'tournaments#display', as: 'display'
  post '/tournaments/submit_scores', to: 'tournaments#submit_scores'
  post '/tournaments/update_scores', to: 'tournaments#update_scores'
  post '/tournaments/set_stale', to: 'tournaments#set_stale'
  post '/tournaments/admin_connection', to: 'tournaments#admin_connection'
  get '/tournaments/status/:id/:court_number/:timestamp', to: 'tournaments#status'

  get '/players', to: 'players#index', as: 'players'
  post '/create_player', to: 'players#create', as: 'create_player'
  get '/players/new', to: 'players#new', as: 'new_player'
  get '/players/:id/edit', to: 'players#edit', as: 'edit_player'

  get '/users', to: 'users#index'

  get '/leaderboard', to: 'players#leaderboard', as: 'leaderboard'

  get '/home', to: 'home#home', as: 'home'
  get '/learn_more', to: 'home#learn_more', as: 'learn_more'
  get '/subscription', to: 'home#subscription', as: 'subscription'
  get '/confirmation', to: 'home#confirmation', as: 'confirmationw'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :users
  resources :teams
  post '/user_deactivate', to: 'users#deactivate', as: 'user_deactivate'
  # post '/user_delete', to: 'users#destroy', as: 'user_delete'
  
  get '/sign_up', to: 'registrations#new'
  
  get 'dashboard', to: 'dashboard#index'
  
  root 'home#home'

  post '/webhooks/stripe', to: 'webhooks#stripe'

  resources :webhooks, only: [] do
    collection do
      post :stripe
    end
  end


  # Add this temporary route to handle redirects from existing checkout sessions
  get '/subscription/success', to: 'subscriptions#success'
  get '/subscription/cancel', to: 'subscriptions#cancel'  

  resources :subscriptions, only: [:new, :create] do
    collection do
      get :success
      get :cancel
    end
  end

  # Add this route to handle POST to singular /subscription
  post '/subscription', to: 'subscriptions#create'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_params

  def index
    @tournaments = Tournament.all.order(created_at: :desc)
    @tournaments = @tournaments.where(created_by_id: current_user.id) if current_user&.is_coach?
    
    if current_user&.is_coach?
      @teams = current_user.teams
    else
      @teams = current_user.player_teams
    end
  end

  private

  def set_params
    @positions = [
      ['Setter (S)', 1],
      ['Outside Hitter (OH)', 2],
      ['Opposite/Right Side Hitter (OPPO/RS)', 3],
      ['Middle (M)', 3],
      ['Libero (LIB)', 4],
      ['Defensive Specialist (DS)', 5]
    ]
  end
end

app/views/dashboard/_adhoc_index.html.erb
<% if @tournaments %>
  <% @tournaments.where(adhoc: true).each do |tournament| %>
    <tr class="bg-grey">
      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= tournament.name %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= tournament.created_at.strftime("%b %e, %Y | %l:%M %p") %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= "#{tournament.city}, #{tournament.state}" %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= tournament.players.count %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= tournament.tournament_time %>m</td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= tournament.break_time %>m</td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= tournament.court_names_pretty %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= tournament&.rounds_configured.join(', ') %></td>
      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500"><%= tournament&.rounds_finalized.join(', ') %></td>
      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
      <% if tournament.rounds_configured.include?(1) %>
        <%= link_to "Round 1", administration_tournament_path(tournament, 1), class: "text-indigo-600 hover:text-indigo-900" %> |
      <% end %>
      <% if tournament.rounds_configured.include?(2) %>
        <%= link_to "Round 2", administration_tournament_path(tournament, 2), class: "text-indigo-600 hover:text-indigo-900" %> |
      <% end %>
      <% if tournament.rounds_finalized.include?(tournament.rounds_configured.last.to_i) %>
        <%= link_to "Results", results_tournament_path(tournament), class: "text-indigo-600 hover:text-indigo-900" %> |
      <% end %>
        <%= link_to "Edit", edit_tournament_path(tournament), class: "text-indigo-600 hover:text-indigo-900" %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/dashboard/index.html.erb
<div data-controller="portal" class="mx-auto">
  <div class="flex gap-2 items-center border-b-2 pb-1 flow-root">
    <h2 class="text-center text-4xl font-bold tracking-tight leading-none text-gray-900 md:text-4xl lg:text-4xl dark:text-white float-left">Tournaments</h2>
    <button 
      type="button" 
      class="float-right text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-md px-5 py-1 text-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
      data-action="portal#newAdhocTournamentClick">[+] Adhoc Tournament
    </button>
    <button 
      type="button" 
      class="float-right text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-md px-5 py-1 text-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
      data-action="portal#newTournamentClick">[+] Registered Players Tournament
    </button>
  </div>
  <div id="tournaments" class="min-w-full">
    <div class="flex flex-col">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <%= render "tournaments/tournaments_table" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/landing.html.erb
<div class="bg-white">
  <!-- Header -->
  <header class="absolute inset-x-0 top-0 z-50">
    <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Product</a>

        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">About Us</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">&rarr;</span></a>
      </div>
    </nav>
    <!-- Mobile menu, show/hide based on menu open state. -->
    <div class="lg:hidden" role="dialog" aria-modal="true">
      <!-- Background backdrop, show/hide based on slide-over state. -->
      <div class="fixed inset-0 z-50"></div>
      <div class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
        <div class="flex items-center justify-between">
          <a href="#" class="-m-1.5 p-1.5">
            <span class="sr-only">Your Company</span>
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
          </a>
          <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700">
            <span class="sr-only">Close menu</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="mt-6 flow-root">
          <div class="-my-6 divide-y divide-gray-500/10">
            <div class="space-y-2 py-6">
              <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Product</a>

              <a href="#" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">About Us</a>
            </div>
            <div class="py-6">
              <a href="#" class="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Log in</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

  <main class="isolate">
    <!-- Hero section -->
    <div class="relative pt-14">
      <div class="py-24 sm:py-32">
        <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80">
          <svg class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678">
            <path fill="url(#9b2541ea-d39d-499b-bd42-aeea3e93f5ff)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
            <defs>
              <linearGradient id="9b2541ea-d39d-499b-bd42-aeea3e93f5ff" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
                <stop stop-color="#9089FC" />
                <stop offset="1" stop-color="#FF80B5" />
              </linearGradient>
            </defs>
          </svg>
        </div>
        <div class="mx-auto max-w-7xl px-6 lg:px-8">
          <div class="mx-auto max-w-2xl text-center">
            <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">TourneyChamp</h1>
            <p class="mt-6 text-lg leading-8 text-gray-600">You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don’t know exactly when we turned on each other, but I know that seven of us survived the slide… and only five made it out. Now we took an oath, that I’m breaking now. We said we’d say it was the snow that killed the other two, but it wasn’t. Nature is lethal but it doesn’t hold a candle to man.</p>

                        <p class="mt-6 text-lg leading-8 text-gray-600">Look, just because I don’t be givin’ no man a foot massage don’t make it right for Marsellus to throw Antwone into a glass motherfuckin’ house, fuckin’ up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, ’cause I’ll kill the motherfucker, know what I’m sayin’?</p>

                        <p class="mt-6 text-lg leading-8 text-gray-600">The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother’s keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.</p>
            <div class="mt-10 flex items-center justify-center gap-x-6">
              <a href="#" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Contact Us</a>
              <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Log in <span aria-hidden="true">→</span></a>
            </div>
          </div>
        </div>
        <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]">
          <svg class="relative left-[calc(50%+3rem)] h-[21.1875rem] max-w-none -translate-x-1/2 sm:left-[calc(50%+36rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678">
            <path fill="url(#b9e4a85f-ccd5-4151-8e84-ab55c66e5aa1)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
            <defs>
              <linearGradient id="b9e4a85f-ccd5-4151-8e84-ab55c66e5aa1" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
                <stop stop-color="#9089FC" />
                <stop offset="1" stop-color="#FF80B5" />
              </linearGradient>
            </defs>
          </svg>
        </div>
      </div>
    </div>




    <!-- Testimonial section -->
    <div class="mx-auto mt-32 max-w-7xl sm:px-6 lg:px-8">
      <div class="relative overflow-hidden bg-gray-900 py-20 px-6 shadow-xl sm:rounded-3xl sm:py-24 sm:px-10 md:px-12 lg:px-20">
        <img class="absolute inset-0 h-full w-full object-cover brightness-150 saturate-0" src="https://images.unsplash.com/photo-1601381718415-a05fb0a261f3?ixid=MXwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8ODl8fHxlbnwwfHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1216&q=80" alt="">
        <div class="absolute inset-0 bg-gray-900/90 mix-blend-multiply"></div>
        <svg viewBox="0 0 1097 845" aria-hidden="true" class="absolute -top-56 -left-80 w-[68.5625rem] transform-gpu blur-3xl">
          <path fill="url(#68eb76c4-2bc9-4928-860e-70adf05719f4)" fill-opacity=".45" d="M301.174 646.641 193.541 844.786 0 546.172l301.174 100.469 193.845-356.855c1.241 164.891 42.802 431.935 199.124 180.978 195.402-313.696 143.295-588.18 284.729-419.266 113.148 135.13 124.068 367.989 115.378 467.527L811.753 372.553l20.102 451.119-530.681-177.031Z" />
          <defs>
            <linearGradient id="68eb76c4-2bc9-4928-860e-70adf05719f4" x1="1097.04" x2="-141.165" y1=".22" y2="363.075" gradientUnits="userSpaceOnUse">
              <stop stop-color="#776FFF" />
              <stop offset="1" stop-color="#FF4694" />
            </linearGradient>
          </defs>
        </svg>
        <svg viewBox="0 0 1097 845" aria-hidden="true" class="hidden md:absolute md:bottom-16 md:left-[50rem] md:block md:w-[68.5625rem] md:transform-gpu md:blur-3xl">
          <path fill="url(#68eb76c4-2bc9-4928-860e-70adf05719f4)" fill-opacity=".25" d="M301.174 646.641 193.541 844.786 0 546.172l301.174 100.469 193.845-356.855c1.241 164.891 42.802 431.935 199.124 180.978 195.402-313.696 143.295-588.18 284.729-419.266 113.148 135.13 124.068 367.989 115.378 467.527L811.753 372.553l20.102 451.119-530.681-177.031Z" />
        </svg>
        <div class="relative mx-auto max-w-2xl lg:mx-0">
          <figure>
            <blockquote class="mt-6 text-lg font-semibold text-white sm:text-xl sm:leading-8">
              <p>“Amet amet eget scelerisque tellus sit neque faucibus non eleifend. Integer eu praesent at a. Ornare arcu gravida natoque erat et cursus tortor consequat at. Vulputate gravida sociis enim nullam ultricies habitant malesuada lorem ac.”</p>
            </blockquote>
            <figcaption class="mt-6 text-base text-white">
              <div class="mt-1">The TourneyChamp Team</div>
            </figcaption>
          </figure>
        </div>
      </div>
    </div>

  </main>

  </div>
</div>