config/routes.rb
Rails.application.routes.draw do
  resources :tournaments, except: :show do
    member do
      get 'results'
      post 'team_scores_update'
    end
  end

  get '/user_role_request/:id/approve', to: 'user_role_requests#approve', as: 'approve_user_role_request'
  get '/user_role_request/:id/deny', to: 'user_role_requests#deny', as: 'deny_user_role_request'

  get '/profile', to: 'users#profile'

  get '/tournaments/administration/:id/:round', to: 'tournaments#administration', as: 'administration_tournament'
  get '/tournaments/display/:id/:court', to: 'tournaments#display', as: 'display'
  post '/tournaments/submit_scores', to: 'tournaments#submit_scores'
  post '/tournaments/update_scores', to: 'tournaments#update_scores'
  post '/tournaments/set_stale', to: 'tournaments#set_stale'
  post '/tournaments/admin_connection', to: 'tournaments#admin_connection'
  get '/tournaments/status/:id/:court_number/:timestamp', to: 'tournaments#status'

  get '/players', to: 'players#index', as: 'players'
  post '/create_player', to: 'players#create', as: 'create_player'
  get '/players/new', to: 'players#new', as: 'new_player'
  get '/players/:id/edit', to: 'players#edit', as: 'edit_player'

  get '/users', to: 'users#index'

  get '/leaderboard', to: 'players#leaderboard', as: 'leaderboard'

  get '/home', to: 'home#home', as: 'home'
  get '/learn_more', to: 'home#learn_more', as: 'learn_more'
  get '/subscription', to: 'home#subscription', as: 'subscription'
  get '/confirmation', to: 'home#confirmation', as: 'confirmationw'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :users
  resources :teams
  post '/user_deactivate', to: 'users#deactivate', as: 'user_deactivate'
  # post '/user_delete', to: 'users#destroy', as: 'user_delete'
  
  get '/sign_up', to: 'registrations#new'
  
  get 'dashboard', to: 'dashboard#index'
  
  root 'home#home'

  post '/webhooks/stripe', to: 'webhooks#stripe'

  resources :webhooks, only: [] do
    collection do
      post :stripe
    end
  end


  # Add this temporary route to handle redirects from existing checkout sessions
  get '/subscription/success', to: 'subscriptions#success'
  get '/subscription/cancel', to: 'subscriptions#cancel'  

  resources :subscriptions, only: [:new, :create] do
    collection do
      get :success
      get :cancel
    end
  end

  # Add this route to handle POST to singular /subscription
  post '/subscription', to: 'subscriptions#create'

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_user, only: %i[edit update destroy]
  before_action :set_positions
  before_action :check_subscription, unless: :skip_subscription_check?
  
  def leaderboard
    players = current_user.players.where(is_ghost_player: false, is_on_leaderboard: true)
    @players = []
    players.each do |player|
      @players << [player.profile_picture, player.full_name, player.statistics, player.initials] if player.statistics[:sets_played] > 0
    end
  end

  def index
    @title = 'Player Management'
    players =
      if params[:sort]
        current_user.players.where(is_ghost_player: false).order(params[:sort])
      else
        current_user.players.where(is_ghost_player: false)
      end
    @players_one_off = players.all.where(is_one_off: true, is_active: true).where('created_at > ?', 2.days.ago)
    @players_team = players.all.where(is_one_off: false, is_active: true)
  end

  def new
    @type = if params[:type] == 'team'
              'Team'
            else
              'One Off'
            end
    @submit_button_text = 'Create Player'
    @user = User.new
  end

  def edit
    @submit_button_text = 'Update'
  end

  def create
    @user = User.new(user_params)
    @user.coach = current_user

    respond_to do |format|
      if @user.save(validate: false)
        format.html { redirect_to players_path, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to players_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      elsif @user.errors
        @teams = @user.teams
        format.html { redirect_to players_path, alert: @user.errors.full_messages[0] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { head :no_content }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_positions
    @positions =
      [
        ['Setter (S)', 1],
        ['Outside Hitter (OH)', 2],
        ['Opposite/Right Side Hitter (OPPO/RS)', 3],
        ['Middle (M)', 3],
        ['Libero (LIB)', 4],
        ['Defensive Specialist (DS)', 5]
      ]
  end

  def user_params
    params.permit(
      :email,
      :first_name,
      :last_name,
      :nick_name,
      :address,
      :city,
      :state,
      :zip,
      :phone_number,
      :jersey_number,
      :position,
      :gender,
      :contact_1_name,
      :contact_1_phone,
      :contact_1_address,
      :contact_2_name,
      :contact_2_phone,
      :contact_2_address,
      :date_of_birth,
      :profile_picture
    )
  end
end

app/views/players/_dashboard.html.erb
<div class="md:grid md:grid-cols-4 md:gap-6 max-w-7xl mx-auto">
  <div class="mt-5 md:mt-0 md:col-span-1">
    <%= render partial: "users/profile_picture", locals: { user: current_user } %>
    <div class="w-full flex justify-center">
      <a data-modal-toggle="enterInviteCode" class="inline-flex items-center px-2.5 py-1.5 mt-4 border border-transparent text-lg font-medium rounded text-indigo-500 hover:text-indigo-700 cursor-pointer text-center">Enter Invite Code</a>
    </div>
  </div>

  <div class="mt-5 md:mt-0 md:col-span-3">
    <div class="mt-4">
      <ul id="tabs" class="inline-flex w-full px-1 pt-2 ">
        <li class="px-4 py-2 -mb-px font-semibold text-gray-900 border-b-2 border-blue-400"><a id="profile-tab" href="#profile">Profile</a></li>
        <li class="px-4 py-2 font-semibold text-gray-900"><a href="#teams">My Teams</a></li>
      </ul>
      <div id="tab-contents">
        <div id="profile" class="p-4">
          <%= render partial: "users/form", locals: { user: current_user } %>
        </div>
        <div id="teams" class="hidden p-4">
          <%= render "players/teams/index" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="enterInviteCode" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">

  <div class="relative p-4 w-full max-w-2xl h-full md:h-auto" data-controller="invite">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <!-- Modal header -->
      <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
        <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
          Enter Invite Code
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="enterInviteCode">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <input type="text" class="w-full px-2 py-2 text-sm border rounded-md focus:border-blue-400 focus:outline-none focus:ring-1 focus:ring-blue-500" data-invite-target="inviteCode" data-action="input->invite#lookupInviteCode" />
        <div class="pb-4 text-center text-sm hidden" data-invite-target="teamNameContainer">
          You will be joining <span data-invite-target="teamName" class="text-blue-500 font-bold"></span>.
        </div>
        <div class="pb-4 text-center text-sm text-red-500 hidden" data-invite-target="error">
          Invite code invalid.
        </div>
      </div>
      <!-- Modal footer -->
      <div class="flex justify-end p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
        <button data-invite-target="joinTeamButton" data-modal-toggle="enterInviteCode" type="button" class="disabled:bg-gray-400 disabled:hover:bg-gray-400 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" data-action="click->invite#joinTeam">Join team</button>
      </div>
    </div>
  </div>
</div>

<script>
  var tabsContainer = document.querySelector("#tabs");
  var tabTogglers = tabsContainer.querySelectorAll("a");

  tabTogglers.forEach(function(toggler) {
    toggler.addEventListener("click", function(e) {
      e.preventDefault();

      let tabName = this.getAttribute("href");
      let tabContents = document.querySelector("#tab-contents");

      for (let i = 0; i < tabContents.children.length; i++) {
        tabTogglers[i].parentElement.classList.remove("border-blue-400", "border-b-4", "border-b-2", "-mb-px");
        tabContents.children[i].classList.remove("hidden");

        if ("#" + tabContents.children[i].id === tabName) {
          continue;
        }
        tabContents.children[i].classList.add("hidden");
      }
      e.target.parentElement.classList.add("border-blue-400", "border-b-4", "-mb-px");
    });
  });

  if (location.hash) {
    document.querySelector(`a[href='${location.hash}']`).click();
  } else {
    document.getElementById("profile-tab").click();
  }

</script>

app/views/players/_form.html.erb
<%= form_with  url: "/create_player", method: :post do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <div class="my-12 sm:mt-0">
      <div class="md:grid md:grid-cols-4 md:gap-6">
        <div class="mt-5 md:mt-0 md:col-span-3">
          <div class="overflow-hidden sm:rounded-md">
            <div class="px-4 py-5 bg-white sm:p-6">
              <div class="flex flex-col gap-6">
                <% if params[:action] != "new" %>
                  <div>
                    <h2 class="text-2xl leading-6 font-medium text-gray-900 mb-2">Editing: User <%= "#{user.full_name}" %></h2>
                    <span class="block text-sm"><label class="font-semibold text-gray-700">Admin: </label><%= user.is_admin %> |
                   <label class="font-semibold text-gray-700">Coach: </label><%= user.is_coach %> |
                   <label class="font-semibold text-gray-700">Player: </label><%= user.is_player %></span>
                  </div>
                <% end %>
                                  <label class="block text-xl font-medium text-gray-700">Primary Information</label>
                <div class="flex gap-6">


                  <div class="flex-1">
                    <label for="first_name" class="block text-sm font-medium text-gray-700">First name</label>
                    <%= form.text_field :first_name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: 'Required' %>
                  </div>
                  <div class="flex-1">
                    <label for="last_name" class="block text-sm font-medium text-gray-700">Last name</label>
                    <%= form.text_field :last_name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: 'Required'  %>
                  </div>
                </div>
                <div class="flex justify-end">
           
                  <%= form.submit value: @submit_button_text, class: "float-right text-white bg-blue-700 hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-md px-5 py-1 text-center mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
                  <%= link_to 'Cancel', players_path, class: "py-1" %>     
                </div>


                <% if params[:type] == 'team' %>
                <br>

                  <label class="block text-xl font-medium text-gray-700">Optional Information</label>

                  <div class="flex gap-6">
                    <div class="flex-1">
                      <label for="email" class="block text-sm font-medium text-gray-700">Email address</label>
                      <%= form.text_field :email, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md", placeholder: 'A placeholder will be automatically assigned if left empty' %>
                    </div>
                    <div class="flex-1">
                      <label for="nick_name" class="block text-sm font-medium text-gray-700">Nick Name</label>
                      <%= form.text_field :nick_name, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                  </div>

                  <div class="col-span-6">
                    <label for="address" class="block text-sm font-medium text-gray-700">Street address</label>
                    <%= form.text_field :address, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                  </div>

                  <div class="flex gap-6">
                    <div class="flex-1">
                      <label for="city" class="block text-sm font-medium text-gray-700">City</label>
                      <%= form.text_field :city, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                    <div class="flex-1">
                      <label for="state" class="block text-sm font-medium text-gray-700">State / Province</label>
                      <%= form.text_field :state, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                    <div class="flex-1">
                      <label for="zip" class="block text-sm font-medium text-gray-700">ZIP / Postal code</label>
                      <%= form.text_field :zip, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                  </div>

                  <div class="flex-1">
                    <label for="phone_number" class="block text-sm font-medium text-gray-700">Phone Number</label>
                    <%= form.text_field :phone_number, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                  </div>

                  <div class="flex gap-6">
                    <div class="flex-1">
                      <label for="date_of_birth" class="block text-sm font-medium text-gray-700">Date of Birth</label>
                      <%= form.date_field :date_of_birth, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                    <div class="flex-1">
                      <label for="gender" class="block text-sm font-medium text-gray-700">Gender</label>
                      <%= form.text_field :gender, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                  </div>


                  <div class="flex gap-6">
                    <div class="flex-1">
                      <label for="jersey_number" class="block text-sm font-medium text-gray-700">Jersey Number</label>
                      <%= form.text_field :jersey_number, class: "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
                    </div>
                    <div class="flex-1">
                      <label for="position" class="block text-sm font-medium text-gray-700">Position<span class="text-gray-400"></span></label>
                      <%= form.select :position, @positions, { :include_blank => "--" }, id: "position", class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:border-indigo-500 sm:text-sm rounded-md" %>
                    </div>
                  </div>
                <% end %>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/players/_players_table.html.erb
<% if players.count > 0 %>
  <div id="users" class="min-w-full">
    <% if @players_one_off.count > 0 && @players_team.count > 0 && type == "one_off" %>
      <span class="font-semibold">One-Off Players</span><span class="font-light font-medium italic text-gray-500 float-right"> Note: One-off players will be erased 24 hours after creation.</span> 
    <% elsif @players_one_off.count > 0 && @players_team.count > 0 && type == "team" %>
      <span class="font-semibold">Team Players</span>
    <% else %>
    <% end %>

    <div class="flex flex-col">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table id="<%= type %>" class="min-w-full divide-y divide-gray-300">
              <thead class="bg-gray-50">
                <tr>
                  <th scope="col" class="underline px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">&nbsp;</th>
                  <th scope="col" class="underline px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Last Name</th>
                  <th scope="col" class="underline px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">First Name</th>
                  <% if type == "team" %>
                    <th scope="col" class="underline px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Phone</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Jersey</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Position</th>
                  <% else %>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">&nbsp;</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">&nbsp;</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">&nbsp;</th>
                      <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">&nbsp;</th>                                            
                  <% end %>
                  <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">&nbsp;</th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">&nbsp;</span>
                  </th>

                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 bg-white">
                <% players&.each do |user| %>
                  <tr 
                    class="bg-grey" 
                    data-controller="user" 
                    data-user-id-value="<%= user.id %>" 
                    data-user-type-value="player"
                    data-user-name-value="<%= user.full_name_proper %>" 
                  >
                    <td class="px-1 py-1 whitespace-nowrap text-sm font-sm text-gray-900">
                      <div class="relative aspect-square bg-gray-300 rounded-[50%] flex justify-center items-center text-[10px] mt-0 w-12 h-12 border-2 border-gray-600 text-gray-600">
                        <% if user.profile_picture.attached? %>
                          <%= image_tag(user.profile_picture, class: 'rounded-[50%] absolute top-0 bottom-0 left-0 right-0 w-12 h-11 object-cover object-center') %>
                        <% else %>
                          <%= user.initials %>
                        <% end %>
                      </div>
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= user.last_name %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= user.first_name %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= user.email if !user.is_one_off %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= user.phone_number %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= user.jersey_number %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= user.position %></td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      <a href="<%= edit_player_path(user, is_one_off: user.is_one_off) %>">
                        <button 
                          class="text-md py-0.5 px-5 text-md font-medium text-red-700 focus:outline-none bg-white rounded-full border-2 border-red-700 hover:bg-gray-100 hover:text-red-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-red-700 dark:border-gray-600 dark:hover:text-black dark:hover:bg-gray-200">
                          Edit
                        </button>   
                      </a>                    
                    </td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      <button 
                        id="delete-button"
                        data-action="click->user#deactivate"
                        type="button"                         
                        class="text-md py-0.5 px-5 text-md font-medium text-gray-400 focus:outline-none bg-white rounded-full border-2 border-gray-400 hover:bg-gray-100 focus:z-10 focus:ring-4 focus:ring-gray-200">
                        Delete
                      </button>   
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>

<% end %>
<br>

<script>
  $(document).ready( function () {
    if ("<%= type %>" == "team") {
      $('#<%= type %>').dataTable( {
        columnDefs: [
          { orderable: false, targets: [0, 7, 8] }
        ],
        order: [[1, 'asc']],
        dom: 'rtf',
        pageLength: 250
      } );
    }

    if ("<%= type %>" == "one_off") {
      $('#<%= type %>').dataTable( {
        columnDefs: [
          { orderable: false, targets: [0, 3, 4, 5, 6, 7, 8] }
        ],        
        order: [[1, 'asc']],
        'targets': [1, 2, 3],
        dom: 'rt',
        pageLength: 250
      } );      
    }
  } );
</script> 

app/views/players/edit.html.erb
<div class="mx-auto md:w-5/6 w-full mb-24">
  <%= render "form_edit", user: @user %>
  <div class="flex-1">
  </div>
</div>

app/views/players/index.html.erb
<div class="mx-auto" data-controller="users">
  <div class="pb-6 flex justify-between items-center">
    <h1 class="text-gray-500 text-3xl tracking-tighter items-center pt-1 font-bold"><%= @title %></h1>
      <div class="flex gap-2 items-center pb-1 flow-root">
        <button 
          type="button" 
          class="float-right text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-full text-md px-5 py-1 text-center mr-2"
          data-action="users#newOneOffPlayer">Create One-Off Player
        </button>       
        <button 
          type="button" 
          class="float-right text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-full text-md px-5 py-1 text-center mr-2"
          data-action="users#newTeamPlayer">Create Team Player
        </button> 
      </div>    
    <%# link_to 'New Player', new_user_path, class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
  <% if @players_one_off.count + @players_team.count == 0 %>
    <div class="italic text-center text-md font-medium tracking-tight leading-none text-gray-600 md:text-md lg:text-md">
      Such nothingness! <br><br> Add some players to your team!<br><br>
    </div>

    <div class="justify-center flex items-center">
        <div class="w-1/3 rounded-lg border-dashed p-4 border-2 border-gray-500 italic text-justify text-sm font-medium text-gray-500 md:text-md lg:text-md">
          <br>
          Create a "One-Off Player" when the player will be temporary or for an adhoc Tournament situation. The One-Off player
          can be entered quickly without an email or contact information, where you're not looking to track long-term statistics.<br><br>
          Members of your Team should be "Team Players". A Team Player is a regular member of your team, where you'll generally
          have all of their information available and entered. As you create tournaments, statistics will be generated on the Leaderboard.
          As you create more Tournaments, the data will become more accurate.
          <br><br>
          Of noteworthiness when creating a Player, is the "show on Leaderboard" property. You can add or remove a Player from your Leaderboard page statistics with this feature.
          <br><br>
        </div>
    </div>

  <% end %>
  <%= render "players_table", players: @players_one_off, type: "one_off" %>
  <%= render "players_table", players: @players_team, type: "team" %>
</div>

app/views/players/leaderboard.html.erb
<div class="mx-auto" data-controller="users">
  <div class="pb-6 flex justify-between items-center">
    <h1 class="text-gray-500 text-3xl tracking-tighter items-center pt-1 font-bold"><%= @title %></h1>   
    <%# link_to 'New Player', new_user_path, class: "inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
  <% if @players.count == 0 %>
    <div class="text-center text-md font-medium leading-none text-gray-600 md:text-md lg:text-md">
      Add some players and get some tournaments going first by <%= link_to "clicking here", players_path, class: "text-indigo-600 hover:text-indigo-500" %>!
    </div>

    <!-- Centered, framed image with reduced size, added top margin, and opacity -->
    <div class="max-w-xl mx-auto px-4 mt-12">
      <%= image_tag "sign-up.jpg", 
          class: "w-3/4 mx-auto h-auto rounded-2xl shadow-xl object-cover aspect-[4/3] opacity-50",
          alt: "Get started with Court Ninja" %>
    </div>
  <% end %>

  <% if @players.count != 0 %>
    <%= render "leaderboard_table", players: @players  %>
  <% end %>
</div>

app/views/players/new.html.erb
<div class="mx-auto md:w-5/6 w-full">
  <div class="mb-6">
    <h1 class="font-semibold text-3xl">New <%= @type %> Player</h1>
  </div>
  <%= render "form_new", user: @user, new_player: true %>
</div>